version: "3.8"
services:
  nodeserver:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/usr/src/app

  nginx:
    restart: always
    image: nginx
    volumes:
      - ./frontend/dist:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - nodeserver
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: map-app
    ports:
      - "5433:5432"
    restart: always
